#!/usr/bin/env bash
clear

echo "========== LinuxRE System Information =========="
echo

fastfetch 2>/dev/null || true

echo
echo "========== lsblk =========="
lsblk

echo
echo "========== Memory =========="
free -h

echo
echo "========== CPU =========="
lscpu

echo
echo "========== Network =========="
ip -br addr

echo
echo "Press any key..."
read -n1
